baseURL = "https://blog.devstream.io"
defaultContentLanguage = "en"
languageCode = "en"
hasCJKLanguage = true
title = "DevStream Blog"

theme = "LoveIt"

[params]
  version = "0.2.X"
  [params.header]
    [params.header.title]
      logo = "/images/logo-120px.jpg"
      name = "DevStream Blog"
  [params.page]
    [params.page.toc]
      enable = true
      auto = true

[languages]
  [languages.en]
    weight = 1
    title = "DevStream Blog"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.en.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.en.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.en.menu.main]]
      identifier = "docs"
      pre = ""
      post = ""
      name = "Docs"
      url = "https://docs.devstream.io"
      title = ""
      weight = 4
    [[languages.en.menu.main]]
      identifier = "website"
      pre = ""
      post = ""
      name = "Website"
      url = "https://www.devstream.io"
      title = ""
      weight = 5
    [[languages.en.menu.main]]
      identifier = "github"
      pre = ""
      post = ""
      name = "GitHub"
      url = "https://github.com/devstream-io/devstream"
      title = ""
      weight = 6

  [languages.zh-cn]
    weight = 2
    title = "DevStream部落格"
    # 网站语言, 仅在这里 CN 大写
    languageCode = "zh-CN"
    languageName = "简体中文"
    # 是否包括中日韩文字
    hasCJKLanguage = true
    [[languages.zh-cn.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.zh-cn.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.zh-cn.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.zh-cn.menu.main]]
      identifier = "docs"
      pre = ""
      post = ""
      name = "文档"
      url = "https://docs.devstream.io"
      title = ""
      weight = 4
    [[languages.zh-cn.menu.main]]
      identifier = "website"
      pre = ""
      post = ""
      name = "网站"
      url = "https://www.devstream.io"
      title = ""
      weight = 5
    [[languages.zh-cn.menu.main]]
      identifier = "github"
      pre = ""
      post = ""
      name = "GitHub"
      url = "https://github.com/devstream-io/devstream"
      title = ""
      weight = 6

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
